version: '3.4'

services:
  accomodationdb:
    container_name: accomodationdb
    restart: always
    ports:
      - "27017:27017"

  reservationdb:
    container_name: reservationdb
    restart: always
    ports:
     - "18005:27017"

  search-service:
    container_name: search-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "AccomodationDatabase:ConnectionString=mongodb://accomodationdb:27017"
    depends_on:
      - accomodationdb
    ports:
      - "5000:80"
 
  reservation-service:
    container_name: reservation-service
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - "ReservationsDatabase:ConnectionString=mongodb://reservationdb:27017"
    depends_on:
      - reservationdb
    ports:
      - "5100:80"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: accomodationdb reservationdb
    depends_on:
      - accomodationdb

  mongo-express1:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: reservationdb
    depends_on:
      - reservationdb

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"

