version: '3.4'

services:

  accomodationdb:
    container_name: accomodationdb
    restart: always
    ports:
      - "18007:27017"

  searchdb:
    container_name: searchdb
    restart: always
    ports:
      - "18006:27017"

  reservationdb:
    container_name: reservationdb
    restart: always
    ports:
     - "18005:27017"

  search-service:
    container_name: search-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "AccomodationDatabase:ConnectionString=mongodb://searchdb:27017"
      - "GrpcSearch=http://localhost:5101"
    depends_on:
      - searchdb
    ports:
      - "5000:80"
 
  reservation-service:
    container_name: reservation-service
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - "ReservationsDatabase:ConnectionString=mongodb://reservationdb:27017"
    depends_on:
      - reservationdb
    ports:
      - "5100:80"
      - "5101:80"
      

  accomodation-service:
    container_name: accomodation-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "AccomodationDatabase:ConnectionString=mongodb://accomodationdb:27017"
    depends_on:
      - accomodationdb
    ports:
      - "5200:80"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: searchdb
    depends_on:
      - searchdb

  mongo-express1:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: reservationdb
    depends_on:
      - reservationdb

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"
